version: '3.8'

services:
  weblab-nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dist/apps/frontend:/var/www/frontend
    # ports:
    #   - '3777:80'
    #   - '3778:443'
    network_mode: host
